services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: census-database
    image: burning-man/census-database
    security_opt:
      - apparmor:unconfined
    ports:
      - "3306:3306"
    restart: always
  census:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: census-app
    env_file:
      - ./client/.env.production
    image: burning-man/census-app
    security_opt:
      - apparmor:unconfined
    ports:
      - "3000:3000"
    restart: always
