services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: census-database
    image: burning-man/census-database
    security_opt:
      - apparmor:unconfined
    ports:
      - "3306:3306"
    restart: always
  dnsmasq:
    build:
      context: dnsmasq
      dockerfile: Dockerfile
    container_name: census-dnsmasq
    image: burning-man/census-dnsmasq
    security_opt:
      - apparmor:unconfined
    cap_add: ["NET_ADMIN"]
    ports:
      - "192.168.0.11:53:53"
      - "192.168.0.11:53:53/udp"
    restart: always
  httpd:
    build:
      context: httpd
      dockerfile: Dockerfile
    container_name: census-nginx
    image: burning-man/census-nginx
    security_opt:
      - apparmor:unconfined
    ports:
      - "80:80"
      - "443:443"
    restart: always
  census:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: census-app
    env_file:
      - ./client/.env.production
    image: burning-man/census-app
    security_opt:
      - apparmor:unconfined
    ports:
      - "3000:3000"
    restart: always
