version: "3.8"

services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: census-database
    image: burning-man/census-database
    ports:
      - "3306:3306"
    restart: always
  census:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: census-app
    env_file:
      - ./app/.env.production
    image: burning-man/census-app
    ports:
      - "3000:3000"
    restart: always

